### ISSUE TITLE
Maybe add a refresh property

### ISSUE THREAD

**Issue by mphe** [mphe/SmartShape2D#10]
Add a dummy property to shape_base that marks the shape as dirty.
Can be used to force refreshing the shape.
See also discussion in https://github.com/mphe/SmartShape2D/issues/5.

**Comment by limbonaut** [comment]
Like a custom property editor with a "Refresh" button?

**Comment by mphe** [comment]
Just a regular bool property with a setter that does nothing but marking the shape dirty. When you click the checkbox in the inspector, it won't change, but the setter will be called and the shape refreshes eventually.
