### ISSUE TITLE
Do something with normal textures

### ISSUE THREAD

**Issue by limbonaut** [mphe/SmartShape2D#11]
`_draw_mesh()` no longer accepts normal textures.

On a cursory investigation, it seems that normal textures are used together with CanvasTexture. 
Should we cut all the fields and code related to normal textures? Maybe need a note in the README about it for those who will do conversion from 3.x.

**Comment by mphe** [comment]
Yes, exactly. Remove all normal texture code as it's now handled in CanvasTexture implicitly. A conversion note in the readme would be a good idea, too. There might be more to come in that regard, though. I'll create another issue for tracking documentation stuff.
