### ISSUE TITLE
Documentation for migrating to 4.0

### ISSUE THREAD

**Issue by mphe** [mphe/SmartShape2D#12]
- Normal textures are now included in CanvasTexture
- Legacy shapes don't exist anymore

**Comment by limbonaut** [comment]
Godot 4 no longer offers 'repeat' import option for textures.
SOLUTION: Use CanvasTexture and set repeat there.

**Comment by mphe** [comment]
`git submodule update --init --recursive` after cloning to download Gut once #21 is merged.
