### ISSUE TITLE
UndoRedo seems to be working unreliably

### ISSUE THREAD

**Issue by limbonaut** [mphe/SmartShape2D#20]
Sometimes it works, and sometimes it prints: "Nothing to undo", or worse - undoes something else unrelated to last action.

**Comment by limbonaut** [comment]
Looking at the editor source code, operating on UndoRedo object directly is probably not fully supported. Manager class maintains a history of actions performed in a list. And operating on UndoRedo directly will not trigger creation of those actions, and will not register a proper action in the history undo stack.

Since we don't use version_history anymore, I think I'll rewrite undo redo code to use manager class instead.

**Comment by mphe** [comment]
Should be easier since undo redo code got simplified after a844bfc.
