### ISSUE TITLE
A case of infinite recursion in SS2D_Shape_Closed

### ISSUE THREAD

**Issue by limbonaut** [mphe/SmartShape2D#22]
Here's a reproduction code:
```
	var sc := SS2D_Shape_Closed.new()
	sc._points = SS2D_Point_Array.new()
```

**Comment by mphe** [comment]
Do you also have this weird Godot bug where it jumps right back to the latest stack frame when you click on any stack frame in the debugger? Strangely, I can't reproduce that bug in simple project, only here.

**Comment by limbonaut** [comment]
I do have that bug and stopping execution also clears stack and errors.

I found the source of issue. The "setter" is overridden in shape_closed. It's here:
https://github.com/mphe/SmartShape2D/blob/a2e29eac17d5e991c4d9e1beb62a51cb0e97473b/addons/rmsmartshape/shapes/shape_closed.gd#L49

**Comment by mphe** [comment]
I'll fix it.
I just saw there are even more overridden methods that are mostly copy&paste versions of the original ones in shape_base.
