### ISSUE TITLE
Resource.duplicate(true) doesn't duplicate subresources in Array or Dictionary

### ISSUE THREAD

**Issue by limbonaut** [mphe/SmartShape2D#32]
Related to #4.

Because of this behavior, `set_point_array(make_unique=true)` is not working as expected. `SS2D_Point` resources are not duplicated, when `SS2D_Point_Array` is duplicated. Only dictionary that holds them is duplicated, preserving `SS2D_Point` references that are stored as dictionary values.

This is a part of deeper design issue involving copy-pasting of shapes, meta shapes and sharing/not sharing shape properties. At this moment, copy-paste of a shape produces a shape copy in a state that is not easily fixable via UI.

**Comment by mphe** [comment]
So, the engine internal implementation of `Resource` does not pass the deep copy parameter of `duplicate` to the `duplicate` call of its array/dictionary properties?
That sounds like an engine bug.

**Comment by limbonaut** [comment]
And I found the root of the problem:
https://github.com/godotengine/godot/blob/fc7adaab7b3856a7831d402ea2bbb27efe7b7d8a/core/variant/variant_setget.cpp#L1889-L1900

> So, the engine internal implementation of `Resource` does not pass the deep copy parameter of `duplicate` to the `duplicate` call of its array/dictionary properties?

It passes, they don't act on it as expected it seems. Only non-Object Variant values are deep-copied.

**Comment by mphe** [comment]
What the hell. I found a related issue here: https://github.com/godotengine/godot/issues/37162. The documentation could really be more clear on this.

Alright, so we need to add duplicate back, at least in some classes, under a different name to not override the internal duplicate, manually deep copy affected properties, and then adapt other code to use the custom duplicate function.
