### ISSUE TITLE
Fix various cases of shadowing native methods

### ISSUE THREAD

**Issue by mphe** [mphe/SmartShape2D#5]
See also the discussion in https://github.com/godotengine/godot/issues/55024.

**Comment by limbonaut** [comment]
About `set_light_mask()`, it seems to be used in one place only in the code base. Perhaps we can either rename the method, or move the code to where it is used.

[set_light_mask() shadowing](https://github.com/mphe/SmartShape2D/blob/gd4/addons/rmsmartshape/shapes/shape_base.gd#L246)

**Comment by mphe** [comment]
It's overriding the setter for the light mask so if the user changes the light mask in the editor, the new value will be propagated to all children. Hence, renaming doesn't help.

Unfortunately, there aren't any signals that are triggered when the light mask changes. I also tested if the `draw`, `item_rect_changed`, or `visibility_changed` signals get triggered but without success.

Then I checked the [source](https://github.com/godotengine/godot/blob/013a45706897af989703b944c7cd5f4f58a6c060/scene/main/canvas_item.h#L229) for CanvasItem and apparently `set_light_mask` is virtual, so we might actually get away with overriding it, ignoring the warning, and adding a fat warning comment.

Another option would be to remove the function and instead add a "refresh" property that updates the shape, similar to the one in shape_meta:
https://github.com/mphe/SmartShape2D/blob/4687822f2df5a9745d388ed6f56166734405199b/addons/rmsmartshape/shapes/shape_meta.gd#L10
Or we could add another button to the UI to force update the shape, but I think I prefer the refresh-property.

In that case users can press the button to update the shape if they don't see their changes reflected immediately.
Probably useful for more cases than just the light mask. I remember sometimes having to move a vertex so see the shape updating when changing some material properties. So this workaround would fit multiple purposes.

**Comment by limbonaut** [comment]
Well, you said it yourself that shadowed methods won't be called by the engine.

> Then I checked the [source](https://github.com/godotengine/godot/blob/013a45706897af989703b944c7cd5f4f58a6c060/scene/main/canvas_item.h#L229) for CanvasItem and apparently `set_light_mask` is virtual, so we might actually get away with overriding it, ignoring the warning, and adding a fat warning comment.

It is virtual, but only from C++ perspective. Methods that should be virtual in `ClassDB`  are marked so with  `GDVIRTUAL_BIND` macros or a call to `ClassDB::add_virtual_method` inside `_bind_methods`. And I don't see `canvas_item.cpp` do it for `set_light_mask`. So from scripting perspective this method is not virtual.

Just to be sure, I made a test project, and it confirms that "overridden" `set_light_mask` isn't called by the editor, when user changes the mask in inspector.
[set_light_mask_test.zip](https://github.com/mphe/SmartShape2D/files/10913953/set_light_mask_test.zip)

**Comment by mphe** [comment]
> Methods that should be virtual in `ClassDB` are marked so with `GDVIRTUAL_BIND` macros or a call to `ClassDB::add_virtual_method` inside `_bind_methods`. And I don't see `canvas_item.cpp` do it for `set_light_mask`. So from scripting perspective this method is not virtual.

Ah ok, didn't investigate it that much. Something learned again.

Alright, then I'd definitely settle for the refresh property. What do you think?

**Comment by limbonaut** [comment]
I'm not very familiar with the codebase. It seems to me, the intention here is to update `light_mask` for all the render meshes, when required. It is initiated inside `update_render_nodes()`. `update_render_nodes()` is called when shape state is "dirty". The dirty state is checked from `_process` every frame.
So my opinion is that we should just refactor the method and give it a new name.

**Comment by mphe** [comment]
Ah right, it is called by other parts of the code.
Then we need to do that + I would eventually add a refresh property that marks the shape as dirty, because it doesn't detect changes to `light_mask` automatically. Also provides a workaround for other cases where changes are not detected automatically.

**Comment by limbonaut** [comment]
I checked with 3.5.1 and vanilla addon, and the set_light_mask is not called when user changes mask in inspector. If the intention was to react to inspector changes, then it isn't working as intended.

**Comment by mphe** [comment]
Ah, so it never worked. Well then just rename it for now.

**Comment by limbonaut** [comment]
> Then we need to do that + I would eventually add a refresh property that marks the shape as dirty, because it doesn't detect changes to `light_mask` automatically.

Yeah, besides spying on inspector activity, I don't see an easy way to detect these changes.

**Comment by limbonaut** [comment]
`EditorInspector` has signals `edited_object_changed` and `property_edited(property: String)`. We could technically implement setting shape dirty when shape properties are changed. It's a hack, and I'm not sure if it's worth the effort.

**Comment by mphe** [comment]
Hm, I don't think it's worth the effort, especially since it didn't even work the whole time and fixing it goes beyond porting this project to 4.0.

**Comment by limbonaut** [comment]
Is this fully addressed now?

**Comment by mphe** [comment]
I think it's done.
